name: CI/CD Workflow

on:
  workflow_dispatch:

jobs:
  build:
    uses: Dumas-Carvalho/devsecops-workflows/.github/workflows/build-java.yml@main

  test:
    uses: Dumas-Carvalho/devsecops-workflows/.github/workflows/test-java.yml@main
